// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

package strategies.model;

public interface ChangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strategies.Change)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.strategies.Change.Type type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.strategies.Change.Type type = 2;</code>
   * @return The type.
   */
  strategies.model.Change.Type getType();

  /**
   * <code>.strategies.Change.Event event = 3;</code>
   * @return The enum numeric value on the wire for event.
   */
  int getEventValue();
  /**
   * <code>.strategies.Change.Event event = 3;</code>
   * @return The event.
   */
  strategies.model.Change.Event getEvent();

  /**
   * <code>string key = 4;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 4;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>.google.protobuf.Any value = 5;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.google.protobuf.Any value = 5;</code>
   * @return The value.
   */
  com.google.protobuf.Any getValue();
  /**
   * <code>.google.protobuf.Any value = 5;</code>
   */
  com.google.protobuf.AnyOrBuilder getValueOrBuilder();
}
