// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

package strategies.model;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strategies_Game_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strategies_Game_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strategies_GameInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strategies_GameInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strategies_ChunkInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strategies_ChunkInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strategies_Change_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strategies_Change_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strategies_Chunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strategies_Chunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strategies_Player_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strategies_Player_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strategies_Vector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strategies_Vector_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nData.proto\022\nstrategies\032\031google/protobu" +
      "f/any.proto\"M\n\004Game\022!\n\006chunks\030\001 \003(\0132\021.st" +
      "rategies.Chunk\022\"\n\004info\030\002 \001(\0132\024.strategie" +
      "s.GameInfo\"D\n\010GameInfo\022%\n\006chunks\030\001 \003(\0132\025" +
      ".strategies.ChunkInfo\022\021\n\trootChunk\030\002 \001(\t" +
      "\"\211\001\n\tChunkInfo\022\n\n\002id\030\001 \001(\t\022$\n\010position\030\003" +
      " \001(\0132\022.strategies.Vector\022 \n\004size\030\004 \001(\0132\022" +
      ".strategies.Vector\022\023\n\013parentChunk\030\005 \001(\t\022" +
      "\023\n\013childChunks\030\006 \003(\t\"\343\001\n\006Change\022\n\n\002id\030\001 " +
      "\001(\t\022%\n\004type\030\002 \001(\0162\027.strategies.Change.Ty" +
      "pe\022\'\n\005event\030\003 \001(\0162\030.strategies.Change.Ev" +
      "ent\022\013\n\003key\030\004 \001(\t\022#\n\005value\030\005 \001(\0132\024.google" +
      ".protobuf.Any\"\035\n\004Type\022\t\n\005CHUNK\020\000\022\n\n\006PLAY" +
      "ER\020\001\",\n\005Event\022\t\n\005ADDED\020\000\022\013\n\007REMOVED\020\001\022\013\n" +
      "\007UPDATED\020\002\"\252\001\n\005Chunk\022\n\n\002id\030\001 \001(\t\022#\n\007play" +
      "ers\030\002 \003(\0132\022.strategies.Player\022$\n\010positio" +
      "n\030\003 \001(\0132\022.strategies.Vector\022 \n\004size\030\004 \001(" +
      "\0132\022.strategies.Vector\022\023\n\013parentChunk\030\005 \001" +
      "(\t\022\023\n\013childChunks\030\006 \003(\t\"f\n\006Player\022\n\n\002id\030" +
      "\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005isBot\030\003 \001(\010\022\r\n\005ch" +
      "unk\030\004 \001(\t\022$\n\010position\030\005 \001(\0132\022.strategies" +
      ".Vector\"\036\n\006Vector\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002B" +
      "\024\n\020strategies.modelP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_strategies_Game_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_strategies_Game_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strategies_Game_descriptor,
        new java.lang.String[] { "Chunks", "Info", });
    internal_static_strategies_GameInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_strategies_GameInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strategies_GameInfo_descriptor,
        new java.lang.String[] { "Chunks", "RootChunk", });
    internal_static_strategies_ChunkInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_strategies_ChunkInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strategies_ChunkInfo_descriptor,
        new java.lang.String[] { "Id", "Position", "Size", "ParentChunk", "ChildChunks", });
    internal_static_strategies_Change_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_strategies_Change_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strategies_Change_descriptor,
        new java.lang.String[] { "Id", "Type", "Event", "Key", "Value", });
    internal_static_strategies_Chunk_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_strategies_Chunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strategies_Chunk_descriptor,
        new java.lang.String[] { "Id", "Players", "Position", "Size", "ParentChunk", "ChildChunks", });
    internal_static_strategies_Player_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_strategies_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strategies_Player_descriptor,
        new java.lang.String[] { "Id", "Name", "IsBot", "Chunk", "Position", });
    internal_static_strategies_Vector_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_strategies_Vector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strategies_Vector_descriptor,
        new java.lang.String[] { "X", "Y", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
