// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

package strategies.model;

public interface GameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strategies.Game)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .strategies.Chunk chunks = 1;</code>
   */
  java.util.List<strategies.model.Chunk> 
      getChunksList();
  /**
   * <code>repeated .strategies.Chunk chunks = 1;</code>
   */
  strategies.model.Chunk getChunks(int index);
  /**
   * <code>repeated .strategies.Chunk chunks = 1;</code>
   */
  int getChunksCount();
  /**
   * <code>repeated .strategies.Chunk chunks = 1;</code>
   */
  java.util.List<? extends strategies.model.ChunkOrBuilder> 
      getChunksOrBuilderList();
  /**
   * <code>repeated .strategies.Chunk chunks = 1;</code>
   */
  strategies.model.ChunkOrBuilder getChunksOrBuilder(
      int index);

  /**
   * <code>.strategies.GameInfo info = 2;</code>
   * @return Whether the info field is set.
   */
  boolean hasInfo();
  /**
   * <code>.strategies.GameInfo info = 2;</code>
   * @return The info.
   */
  strategies.model.GameInfo getInfo();
  /**
   * <code>.strategies.GameInfo info = 2;</code>
   */
  strategies.model.GameInfoOrBuilder getInfoOrBuilder();
}
