// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

package strategies.model;

/**
 * Protobuf type {@code strategies.GameInfo}
 */
public final class GameInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:strategies.GameInfo)
    GameInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GameInfo.newBuilder() to construct.
  private GameInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GameInfo() {
    chunks_ = java.util.Collections.emptyList();
    rootChunk_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GameInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return strategies.model.Data.internal_static_strategies_GameInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return strategies.model.Data.internal_static_strategies_GameInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            strategies.model.GameInfo.class, strategies.model.GameInfo.Builder.class);
  }

  public static final int CHUNKS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<strategies.model.ChunkInfo> chunks_;
  /**
   * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
   */
  @java.lang.Override
  public java.util.List<strategies.model.ChunkInfo> getChunksList() {
    return chunks_;
  }
  /**
   * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends strategies.model.ChunkInfoOrBuilder> 
      getChunksOrBuilderList() {
    return chunks_;
  }
  /**
   * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
   */
  @java.lang.Override
  public int getChunksCount() {
    return chunks_.size();
  }
  /**
   * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
   */
  @java.lang.Override
  public strategies.model.ChunkInfo getChunks(int index) {
    return chunks_.get(index);
  }
  /**
   * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
   */
  @java.lang.Override
  public strategies.model.ChunkInfoOrBuilder getChunksOrBuilder(
      int index) {
    return chunks_.get(index);
  }

  public static final int ROOTCHUNK_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object rootChunk_ = "";
  /**
   * <code>string rootChunk = 2;</code>
   * @return The rootChunk.
   */
  @java.lang.Override
  public java.lang.String getRootChunk() {
    java.lang.Object ref = rootChunk_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      rootChunk_ = s;
      return s;
    }
  }
  /**
   * <code>string rootChunk = 2;</code>
   * @return The bytes for rootChunk.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRootChunkBytes() {
    java.lang.Object ref = rootChunk_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      rootChunk_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < chunks_.size(); i++) {
      output.writeMessage(1, chunks_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rootChunk_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, rootChunk_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < chunks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, chunks_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(rootChunk_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, rootChunk_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof strategies.model.GameInfo)) {
      return super.equals(obj);
    }
    strategies.model.GameInfo other = (strategies.model.GameInfo) obj;

    if (!getChunksList()
        .equals(other.getChunksList())) return false;
    if (!getRootChunk()
        .equals(other.getRootChunk())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getChunksCount() > 0) {
      hash = (37 * hash) + CHUNKS_FIELD_NUMBER;
      hash = (53 * hash) + getChunksList().hashCode();
    }
    hash = (37 * hash) + ROOTCHUNK_FIELD_NUMBER;
    hash = (53 * hash) + getRootChunk().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static strategies.model.GameInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static strategies.model.GameInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static strategies.model.GameInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static strategies.model.GameInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static strategies.model.GameInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static strategies.model.GameInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static strategies.model.GameInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static strategies.model.GameInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static strategies.model.GameInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static strategies.model.GameInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static strategies.model.GameInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static strategies.model.GameInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(strategies.model.GameInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code strategies.GameInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:strategies.GameInfo)
      strategies.model.GameInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return strategies.model.Data.internal_static_strategies_GameInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return strategies.model.Data.internal_static_strategies_GameInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              strategies.model.GameInfo.class, strategies.model.GameInfo.Builder.class);
    }

    // Construct using strategies.model.GameInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (chunksBuilder_ == null) {
        chunks_ = java.util.Collections.emptyList();
      } else {
        chunks_ = null;
        chunksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      rootChunk_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return strategies.model.Data.internal_static_strategies_GameInfo_descriptor;
    }

    @java.lang.Override
    public strategies.model.GameInfo getDefaultInstanceForType() {
      return strategies.model.GameInfo.getDefaultInstance();
    }

    @java.lang.Override
    public strategies.model.GameInfo build() {
      strategies.model.GameInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public strategies.model.GameInfo buildPartial() {
      strategies.model.GameInfo result = new strategies.model.GameInfo(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(strategies.model.GameInfo result) {
      if (chunksBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          chunks_ = java.util.Collections.unmodifiableList(chunks_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.chunks_ = chunks_;
      } else {
        result.chunks_ = chunksBuilder_.build();
      }
    }

    private void buildPartial0(strategies.model.GameInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.rootChunk_ = rootChunk_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof strategies.model.GameInfo) {
        return mergeFrom((strategies.model.GameInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(strategies.model.GameInfo other) {
      if (other == strategies.model.GameInfo.getDefaultInstance()) return this;
      if (chunksBuilder_ == null) {
        if (!other.chunks_.isEmpty()) {
          if (chunks_.isEmpty()) {
            chunks_ = other.chunks_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureChunksIsMutable();
            chunks_.addAll(other.chunks_);
          }
          onChanged();
        }
      } else {
        if (!other.chunks_.isEmpty()) {
          if (chunksBuilder_.isEmpty()) {
            chunksBuilder_.dispose();
            chunksBuilder_ = null;
            chunks_ = other.chunks_;
            bitField0_ = (bitField0_ & ~0x00000001);
            chunksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getChunksFieldBuilder() : null;
          } else {
            chunksBuilder_.addAllMessages(other.chunks_);
          }
        }
      }
      if (!other.getRootChunk().isEmpty()) {
        rootChunk_ = other.rootChunk_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              strategies.model.ChunkInfo m =
                  input.readMessage(
                      strategies.model.ChunkInfo.parser(),
                      extensionRegistry);
              if (chunksBuilder_ == null) {
                ensureChunksIsMutable();
                chunks_.add(m);
              } else {
                chunksBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              rootChunk_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<strategies.model.ChunkInfo> chunks_ =
      java.util.Collections.emptyList();
    private void ensureChunksIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        chunks_ = new java.util.ArrayList<strategies.model.ChunkInfo>(chunks_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        strategies.model.ChunkInfo, strategies.model.ChunkInfo.Builder, strategies.model.ChunkInfoOrBuilder> chunksBuilder_;

    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public java.util.List<strategies.model.ChunkInfo> getChunksList() {
      if (chunksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(chunks_);
      } else {
        return chunksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public int getChunksCount() {
      if (chunksBuilder_ == null) {
        return chunks_.size();
      } else {
        return chunksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public strategies.model.ChunkInfo getChunks(int index) {
      if (chunksBuilder_ == null) {
        return chunks_.get(index);
      } else {
        return chunksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public Builder setChunks(
        int index, strategies.model.ChunkInfo value) {
      if (chunksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChunksIsMutable();
        chunks_.set(index, value);
        onChanged();
      } else {
        chunksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public Builder setChunks(
        int index, strategies.model.ChunkInfo.Builder builderForValue) {
      if (chunksBuilder_ == null) {
        ensureChunksIsMutable();
        chunks_.set(index, builderForValue.build());
        onChanged();
      } else {
        chunksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public Builder addChunks(strategies.model.ChunkInfo value) {
      if (chunksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChunksIsMutable();
        chunks_.add(value);
        onChanged();
      } else {
        chunksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public Builder addChunks(
        int index, strategies.model.ChunkInfo value) {
      if (chunksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChunksIsMutable();
        chunks_.add(index, value);
        onChanged();
      } else {
        chunksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public Builder addChunks(
        strategies.model.ChunkInfo.Builder builderForValue) {
      if (chunksBuilder_ == null) {
        ensureChunksIsMutable();
        chunks_.add(builderForValue.build());
        onChanged();
      } else {
        chunksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public Builder addChunks(
        int index, strategies.model.ChunkInfo.Builder builderForValue) {
      if (chunksBuilder_ == null) {
        ensureChunksIsMutable();
        chunks_.add(index, builderForValue.build());
        onChanged();
      } else {
        chunksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public Builder addAllChunks(
        java.lang.Iterable<? extends strategies.model.ChunkInfo> values) {
      if (chunksBuilder_ == null) {
        ensureChunksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, chunks_);
        onChanged();
      } else {
        chunksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public Builder clearChunks() {
      if (chunksBuilder_ == null) {
        chunks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        chunksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public Builder removeChunks(int index) {
      if (chunksBuilder_ == null) {
        ensureChunksIsMutable();
        chunks_.remove(index);
        onChanged();
      } else {
        chunksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public strategies.model.ChunkInfo.Builder getChunksBuilder(
        int index) {
      return getChunksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public strategies.model.ChunkInfoOrBuilder getChunksOrBuilder(
        int index) {
      if (chunksBuilder_ == null) {
        return chunks_.get(index);  } else {
        return chunksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public java.util.List<? extends strategies.model.ChunkInfoOrBuilder> 
         getChunksOrBuilderList() {
      if (chunksBuilder_ != null) {
        return chunksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(chunks_);
      }
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public strategies.model.ChunkInfo.Builder addChunksBuilder() {
      return getChunksFieldBuilder().addBuilder(
          strategies.model.ChunkInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public strategies.model.ChunkInfo.Builder addChunksBuilder(
        int index) {
      return getChunksFieldBuilder().addBuilder(
          index, strategies.model.ChunkInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
     */
    public java.util.List<strategies.model.ChunkInfo.Builder> 
         getChunksBuilderList() {
      return getChunksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        strategies.model.ChunkInfo, strategies.model.ChunkInfo.Builder, strategies.model.ChunkInfoOrBuilder> 
        getChunksFieldBuilder() {
      if (chunksBuilder_ == null) {
        chunksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            strategies.model.ChunkInfo, strategies.model.ChunkInfo.Builder, strategies.model.ChunkInfoOrBuilder>(
                chunks_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        chunks_ = null;
      }
      return chunksBuilder_;
    }

    private java.lang.Object rootChunk_ = "";
    /**
     * <code>string rootChunk = 2;</code>
     * @return The rootChunk.
     */
    public java.lang.String getRootChunk() {
      java.lang.Object ref = rootChunk_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rootChunk_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string rootChunk = 2;</code>
     * @return The bytes for rootChunk.
     */
    public com.google.protobuf.ByteString
        getRootChunkBytes() {
      java.lang.Object ref = rootChunk_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rootChunk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string rootChunk = 2;</code>
     * @param value The rootChunk to set.
     * @return This builder for chaining.
     */
    public Builder setRootChunk(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      rootChunk_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string rootChunk = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRootChunk() {
      rootChunk_ = getDefaultInstance().getRootChunk();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string rootChunk = 2;</code>
     * @param value The bytes for rootChunk to set.
     * @return This builder for chaining.
     */
    public Builder setRootChunkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      rootChunk_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:strategies.GameInfo)
  }

  // @@protoc_insertion_point(class_scope:strategies.GameInfo)
  private static final strategies.model.GameInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new strategies.model.GameInfo();
  }

  public static strategies.model.GameInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GameInfo>
      PARSER = new com.google.protobuf.AbstractParser<GameInfo>() {
    @java.lang.Override
    public GameInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GameInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public strategies.model.GameInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

