// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

package strategies.model;

public interface GameInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strategies.GameInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
   */
  java.util.List<strategies.model.ChunkInfo> 
      getChunksList();
  /**
   * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
   */
  strategies.model.ChunkInfo getChunks(int index);
  /**
   * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
   */
  int getChunksCount();
  /**
   * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
   */
  java.util.List<? extends strategies.model.ChunkInfoOrBuilder> 
      getChunksOrBuilderList();
  /**
   * <code>repeated .strategies.ChunkInfo chunks = 1;</code>
   */
  strategies.model.ChunkInfoOrBuilder getChunksOrBuilder(
      int index);

  /**
   * <code>string rootChunk = 2;</code>
   * @return The rootChunk.
   */
  java.lang.String getRootChunk();
  /**
   * <code>string rootChunk = 2;</code>
   * @return The bytes for rootChunk.
   */
  com.google.protobuf.ByteString
      getRootChunkBytes();
}
