// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

package strategies.proto;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strategies_Game_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strategies_Game_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strategies_Chunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strategies_Chunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strategies_Player_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strategies_Player_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_strategies_Vector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_strategies_Vector_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nData.proto\022\nstrategies\")\n\004Game\022!\n\006chun" +
      "ks\030\001 \003(\0132\021.strategies.Chunk\"\200\001\n\005Chunk\022\n\n" +
      "\002id\030\001 \001(\t\022#\n\007players\030\002 \003(\0132\022.strategies." +
      "Player\022$\n\010position\030\003 \001(\0132\022.strategies.Ve" +
      "ctor\022 \n\004size\030\004 \001(\0132\022.strategies.Vector\"W" +
      "\n\006Player\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005is" +
      "Bot\030\003 \001(\010\022$\n\010position\030\004 \001(\0132\022.strategies" +
      ".Vector\"\036\n\006Vector\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002B" +
      "\024\n\020strategies.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_strategies_Game_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_strategies_Game_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strategies_Game_descriptor,
        new java.lang.String[] { "Chunks", });
    internal_static_strategies_Chunk_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_strategies_Chunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strategies_Chunk_descriptor,
        new java.lang.String[] { "Id", "Players", "Position", "Size", });
    internal_static_strategies_Player_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_strategies_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strategies_Player_descriptor,
        new java.lang.String[] { "Id", "Name", "IsBot", "Position", });
    internal_static_strategies_Vector_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_strategies_Vector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_strategies_Vector_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
