// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

package strategies.proto;

public interface GameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:strategies.Game)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .strategies.Chunk chunks = 1;</code>
   */
  java.util.List<strategies.proto.Chunk> 
      getChunksList();
  /**
   * <code>repeated .strategies.Chunk chunks = 1;</code>
   */
  strategies.proto.Chunk getChunks(int index);
  /**
   * <code>repeated .strategies.Chunk chunks = 1;</code>
   */
  int getChunksCount();
  /**
   * <code>repeated .strategies.Chunk chunks = 1;</code>
   */
  java.util.List<? extends strategies.proto.ChunkOrBuilder> 
      getChunksOrBuilderList();
  /**
   * <code>repeated .strategies.Chunk chunks = 1;</code>
   */
  strategies.proto.ChunkOrBuilder getChunksOrBuilder(
      int index);
}
